# Generated by Django 3.1.3 on 2020-11-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUY', '0002_shippingaddress_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
